In [8]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [13]:
data = {
    'area': [2600, 3000, 3200, 3600, 4000],
    'bedrooms': [3.0, 4.0, np.nan, 5.0, 4.0],
    'age': [20, 15, 18, 30, 8],
    'price': [550000, 565000, 610000, 680000, 725000]
}
df = pd.DataFrame(data)

In [10]:
import os
os.makedirs('multiple_linear_regression', exist_ok=True)

In [15]:
df.to_csv("multiple_linear_regression/home_prices.csv", index=False)

In [16]:
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       5.0   30  680000
4  4000       4.0    8  725000

In [18]:
bedroom_median = df["bedrooms"].median()
df["bedrooms"].fillna(bedroom_median, inplace=True)
df

C:\Users\USER\AppData\Local\Temp\ipykernel_18568\1492098684.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["bedrooms"].fillna(bedroom_median, inplace=True)

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       5.0   30  680000
4  4000       4.0    8  725000